language: java
jdk:
- oraclejdk8
after_success: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: oep/i52JDMWldTbz/4wlTMmkp6H0gnnyJRk8zs1gR75rp4CnhKpXdwGhgWeQhJyY4AZp86++s0OKQDJ4xYXQnw2wGMFzIqLh80FRXgVWJJ5GqwYusR1xlhzZ0fZNfmdmF6IC+1gJ1z6Ixjq0iC5nMPIOvxBSPsV+WwYTqdgEQ350v7xDn5xf18St2kJYjMWdtoPr17drt458LRokFDoRKGEM2LmERPMJ8yHVxmELVt+cXQuOHzBWJIMbo0gwzWVeja5YkJYgJcxV4mqCBal2aCwxMFIX8jS759ZrDP1Y4d9DUMJ8IMe6uJyHW+pQ5k8/x7L4IKaABm9stJtn0wTWrmoKrqUq9THLzBC5CINpewOfYlP1f5QxrYhCYLxHvbQMYI68xr7nrRj+Q9eOrzWQtFHuWVWATsAjLf6WH4G3JLaN1TMMi6FbVKjRAZv4StOEaQHA14y+YglJWhwKefe7ePsZsyPGxatDH0rNbkzflctZ4X0+sefKdqlOUq6OKqOtKMHbgP8Y05AI/z+eI3+HB5GtWSsWBfmnPzSSewD87sgFS71G2KmSiluhsXVOBKTm9SLYPWH/OXemAvhTOwowbfZfVtg8qR/ZbDFmlwKRcAp38YCQGsPkOnyFiXvtltAgBJ6egyt/kKpbuQC1ovrItL4MrcvDgGvn7/jCQCka/ek=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: mibac138/Dot-life-simulator
